import './index.css';
import './fonts.css';

import { ReduxProvider, RootLayoutChildWrapper, TranslationsProvider } from '@/components/wrappers';

import { cookies } from 'next/headers';
import initTranslations from '../i18n';
import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';

import { getUserData } from '@/lib/api';
import { UserData } from '@/types';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

type AsyncParams<T> = Promise<T>;

interface RootLayoutProps {
  children: React.ReactNode;
  params: AsyncParams<{
    locale: string;
  }>;
}

const RootLayout: React.FC<RootLayoutProps> = async ({ children, params }) => {

  const { locale } = await params;

  const i18nNamespaces: string[] = ['app'];

  const { resources } = await initTranslations(locale, i18nNamespaces);

  const cookieStore = await cookies();
  const authToken = cookieStore.get('authCookie')?.value;
  let serverUserData: UserData | null = null;
  let signedInFlag = false;
  if (authToken) {
    signedInFlag = true;
    serverUserData = await getUserData(authToken);
  }

  return (
    <html lang={locale} dir={dir(locale)}>
      <body>
        <TranslationsProvider namespaces={i18nNamespaces} locale={locale} resources={resources}>
          <ReduxProvider>
            <RootLayoutChildWrapper serverUserData={serverUserData} signedInFlag={signedInFlag}>
              {children}
            </RootLayoutChildWrapper>
          </ReduxProvider>
        </TranslationsProvider>
      </body>
    </html>
  )
}

export default RootLayout;