import './index.css';
import './fonts.css';

import { loadWordResources } from '@/utils/dataUtils';

import { ReduxProvider, RootLayoutChildWrapper, TranslationsProvider } from '@/components/wrappers';

import { cookies } from 'next/headers';
import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';
import initTranslation from '@/app/i18n';

import { getUserData } from '@/lib/api';
import { UserData } from '@/types';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

type AsyncParams<T> = Promise<T>;

interface RootLayoutProps {
  children: React.ReactNode;
  params: AsyncParams<{
    locale: string;
  }>;
}

const RootLayout: React.FC<RootLayoutProps> = async ({ children, params }) => {

  const { locale } = await params;
  const cookieStore = await cookies();
  const authToken = cookieStore.get('authCookie')?.value;
  const cookieArrayString = cookieStore.get('languageArray')?.value;
  const cookieArray = cookieArrayString ? JSON.parse(cookieArrayString) : null;

  let serverUserData: UserData | null = null;
  let signedInFlag = false;
  if (authToken) {
    signedInFlag = true;
    serverUserData = await getUserData(authToken);
  }

  const languageArray = cookieArray || serverUserData?.languageArray || ['en', 'ja'];
  const { initialWords, wordResources } = loadWordResources(languageArray);

  const { resources } =  await initTranslation(locale);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body>
        <TranslationsProvider 
          locale={locale} 
          resources={resources}
        >
          <ReduxProvider>
            <RootLayoutChildWrapper 
              serverUserData={serverUserData} 
              signedInFlag={signedInFlag}
              initialWords={initialWords}
              wordResources={wordResources}
              languageArray={languageArray}
            >
              {children}
            </RootLayoutChildWrapper>
          </ReduxProvider>
        </TranslationsProvider>
      </body>
    </html>
  )
}

export default RootLayout;